---
name: Lint

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  proselint:
    name: Prose Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Proselint
        run: pip install --quiet --user proselint

      - name: Run Proselint
        run: find . -name '*.md' -exec proselint {} \;
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: DavidAnson/markdownlint-cli2-action@v21
        with:
          globs: '**/*.md'

  prettier-format:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Prettier Dry Run
        run: |
          npx prettier --check "**/*.md" || {
            echo "::error title=Formatting Failed::Some files are not formatted correctly."
            echo "-------------------------------------------------------"
            echo "❌ CHECK FAILED"
            echo "To fix these issues, run the following command locally:"
            echo ""
            echo "    npx prettier --write \"**/*.md\" --prose-wrap always"
            echo ""
            echo "-------------------------------------------------------"
            exit 1
            }
