---
name: Lint

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: articulate/actions-markdownlint@v1
        with:
          config: .markdownlint.yaml
          files: '**/*.md'
          ignore: node_modules
          version: 0.46.1

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Proselint
        run: pip install --quiet --user proselint

      - name: Run Proselint
        run: find . -name '*.md' -exec proselint {} \;
